### PR TITLE
Do not typecheck in production

### LINKED ISSUE #40: Huge performance penalty because of immutable props validation
`NODE_ENV=production` disables React's PropTypes but not ImmutablePropTypes.
After manually removing them I got a 75%(!!!) rendering speed improvement.

I'm using stuff ranging from

```
let somePropType = ImmutablePropTypes.mapContains({
    id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    isProjectLeader: PropTypes.bool,
    isHidden: PropTypes.bool,
    projectLeaderColor: PropTypes.string,
    index: PropTypes.number
});
```

to 

`let listOfSomePropType = ImmutablePropTypes.listOf(somePropType).isRequired`

_Is there a way for me to disable validation in production?_

### PR DESCRIPTION
**Pull request by brenoc**
Fix #40

### CODE REVIEW

**Comment by brenoc** [comment]
I just did the same thing React does:
https://github.com/facebook/react/blob/master/src/isomorphic/classic/types/ReactPropTypes.js#L73-L123

**Comment by maxkostow** [comment]
@HurricaneJames any chance we can merge this?

**Comment by GalenWarren** [comment]
+1 on merge request, thanks.

**Comment by ericlau-solid** [comment]
+1 on merge request as well - i was wondering why my apps perform so slowly after these checks. Not usable for real projects until this is resolved.

**Comment by ianstarz** [comment]
Seems like this is ready to go, what's holding us back here?

**Comment by HurricaneJames** [comment]
only thing holding it back was me being an idiot and not realizing that github had somehow made my spam filter... :( sorry, I had no idea there were pull requests
.

**Comment by ianstarz** [comment]
Thank you @HurricaneJames ! Is there anything that needs to be done to bump and release?

**Pull request merged**
